version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "5001:5001"
    volumes:
      - ./backend:/app
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb+srv://Jo:kvc9jbXlIcp0TRIi@healthtrack01.gyjms.mongodb.net/healthtracker?retryWrites=true&w=majority

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development
